package com.winchannel.mdm.store.model;

import java.util.Date;

import com.winchannel.base.model.BaseDictItem;
import com.winchannel.base.model.BaseOrg;
import com.winchannel.mdm.distributor.model.MdmDistributor;

/**
 * MdmStoreLog generated by MyEclipse Persistence Tools
 */

public class MdmStoreLog implements java.io.Serializable {

	// Fields

	private Long id;

	private Long storeId;

	private BaseDictItem storeChannel;
	private BaseDictItem storeOther;
	private BaseDictItem storeGeo;
	private MdmStore mdmStore;
	private BaseOrg baseOrg;
	private MdmDistributor mdmDistributor;
	private BaseDictItem storeCorp;
	private BaseDictItem storeNature;
	private BaseDictItem storeType;

	private String storeName;

	private String storeAlias;

	private String storeCode;

	private String extCode;

	private String subCode;

	private Long levelCode;

	private String storeAddr;

	private String linkman;

	private String linktel;

	private Date firstItemDate;

	private Date lastItemDate;

	private Long storeLevel;

	private String storeRelationState;

	private String memo1;

	private String memo2;

	private String memo3;

	private String memo4;

	private String memo5;

	private String memo6;

	private String remark;

	private String state;

	private Long sort;

	private String createdBy;

	private Date created;

	private String updatedBy;

	private Date updated;

	private Date startDate;

	private Date endDate;

	// Constructors

	/** default constructor */
	public MdmStoreLog() {
	}

	/** minimal constructor */
	public MdmStoreLog(Long storeId) {
		this.storeId = storeId;
	}

	/** full constructor */
	

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getStoreId() {
		return this.storeId;
	}

	public void setStoreId(Long storeId) {
		this.storeId = storeId;
	}

	
	public BaseDictItem getStoreChannel() {
		return storeChannel;
	}

	public void setStoreChannel(BaseDictItem storeChannel) {
		this.storeChannel = storeChannel;
	}

	public BaseDictItem getStoreOther() {
		return storeOther;
	}

	public void setStoreOther(BaseDictItem storeOther) {
		this.storeOther = storeOther;
	}

	public BaseDictItem getStoreGeo() {
		return storeGeo;
	}

	public void setStoreGeo(BaseDictItem storeGeo) {
		this.storeGeo = storeGeo;
	}

	public MdmStore getMdmStore() {
		return mdmStore;
	}

	public void setMdmStore(MdmStore mdmStore) {
		this.mdmStore = mdmStore;
	}

	public BaseOrg getBaseOrg() {
		return baseOrg;
	}

	public void setBaseOrg(BaseOrg baseOrg) {
		this.baseOrg = baseOrg;
	}

	public MdmDistributor getMdmDistributor() {
		return mdmDistributor;
	}

	public void setMdmDistributor(MdmDistributor mdmDistributor) {
		this.mdmDistributor = mdmDistributor;
	}

	public BaseDictItem getStoreCorp() {
		return storeCorp;
	}

	public void setStoreCorp(BaseDictItem storeCorp) {
		this.storeCorp = storeCorp;
	}

	public BaseDictItem getStoreNature() {
		return storeNature;
	}

	public void setStoreNature(BaseDictItem storeNature) {
		this.storeNature = storeNature;
	}

	public BaseDictItem getStoreType() {
		return storeType;
	}

	public void setStoreType(BaseDictItem storeType) {
		this.storeType = storeType;
	}

	public String getStoreName() {
		return this.storeName;
	}

	public void setStoreName(String storeName) {
		this.storeName = storeName;
	}

	public String getStoreAlias() {
		return this.storeAlias;
	}

	public void setStoreAlias(String storeAlias) {
		this.storeAlias = storeAlias;
	}

	public String getStoreCode() {
		return this.storeCode;
	}

	public void setStoreCode(String storeCode) {
		this.storeCode = storeCode;
	}

	public String getExtCode() {
		return this.extCode;
	}

	public void setExtCode(String extCode) {
		this.extCode = extCode;
	}

	public String getSubCode() {
		return this.subCode;
	}

	public void setSubCode(String subCode) {
		this.subCode = subCode;
	}

	public Long getLevelCode() {
		return this.levelCode;
	}

	public void setLevelCode(Long levelCode) {
		this.levelCode = levelCode;
	}

	public String getStoreAddr() {
		return this.storeAddr;
	}

	public void setStoreAddr(String storeAddr) {
		this.storeAddr = storeAddr;
	}

	public String getLinkman() {
		return this.linkman;
	}

	public void setLinkman(String linkman) {
		this.linkman = linkman;
	}

	public String getLinktel() {
		return this.linktel;
	}

	public void setLinktel(String linktel) {
		this.linktel = linktel;
	}

	public Date getFirstItemDate() {
		return this.firstItemDate;
	}

	public void setFirstItemDate(Date firstItemDate) {
		this.firstItemDate = firstItemDate;
	}

	public Date getLastItemDate() {
		return this.lastItemDate;
	}

	public void setLastItemDate(Date lastItemDate) {
		this.lastItemDate = lastItemDate;
	}

	public Long getStoreLevel() {
		return this.storeLevel;
	}

	public void setStoreLevel(Long storeLevel) {
		this.storeLevel = storeLevel;
	}

	public String getStoreRelationState() {
		return this.storeRelationState;
	}

	public void setStoreRelationState(String storeRelationState) {
		this.storeRelationState = storeRelationState;
	}

	public String getMemo1() {
		return this.memo1;
	}

	public void setMemo1(String memo1) {
		this.memo1 = memo1;
	}

	public String getMemo2() {
		return this.memo2;
	}

	public void setMemo2(String memo2) {
		this.memo2 = memo2;
	}

	public String getMemo3() {
		return this.memo3;
	}

	public void setMemo3(String memo3) {
		this.memo3 = memo3;
	}

	public String getMemo4() {
		return this.memo4;
	}

	public void setMemo4(String memo4) {
		this.memo4 = memo4;
	}

	public String getMemo5() {
		return this.memo5;
	}

	public void setMemo5(String memo5) {
		this.memo5 = memo5;
	}

	public String getMemo6() {
		return this.memo6;
	}

	public void setMemo6(String memo6) {
		this.memo6 = memo6;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Long getSort() {
		return this.sort;
	}

	public void setSort(Long sort) {
		this.sort = sort;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

}