package com.winchannel.mdm.empstore.model;

import com.winchannel.mdm.store.model.MdmStore;

/**
 * MdmEmpStoreItem generated by MyEclipse Persistence Tools
 */

public class MdmEmpStoreItem implements java.io.Serializable {

	// Fields

	private Long itemId;

	private MdmEmpStore mdmEmpStore;

	private MdmStore mdmStore;

	private String storeCode;

	// Constructors

	/** default constructor */
	public MdmEmpStoreItem() {
	}

	/** full constructor */
	public MdmEmpStoreItem(MdmEmpStore mdmEmpStore, MdmStore mdmStore, String storeCode) {
		this.mdmEmpStore = mdmEmpStore;
		this.mdmStore = mdmStore;
		this.storeCode = storeCode;
	}

	// Property accessors

	public Long getItemId() {
		return this.itemId;
	}

	public void setItemId(Long itemId) {
		this.itemId = itemId;
	}

	public MdmEmpStore getMdmEmpStore() {
		return this.mdmEmpStore;
	}

	public void setMdmEmpStore(MdmEmpStore mdmEmpStore) {
		this.mdmEmpStore = mdmEmpStore;
	}

	public MdmStore getMdmStore() {
		return this.mdmStore;
	}

	public void setMdmStore(MdmStore mdmStore) {
		this.mdmStore = mdmStore;
	}

	public String getStoreCode() {
		return this.storeCode;
	}

	public void setStoreCode(String storeCode) {
		this.storeCode = storeCode;
	}

}