package com.winchannel.mdm.empstore.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.winchannel.base.model.BaseEmployee;

/**
 * MdmEmpStore generated by MyEclipse Persistence Tools
 */

public class MdmEmpStore implements java.io.Serializable {

	// Fields

	private Long esId;

	private BaseEmployee baseEmployee;

	private String dateDesc;

	private Date startTime;

	private Date endTime;

	private String remark;

	private String state;

	private String createdBy;

	private Date created;

	private String updatedBy;

	private Date updated;

	private Set mdmEmpStoreItems = new HashSet(0);

	// Constructors

	/** default constructor */
	public MdmEmpStore() {
	}

	/** full constructor */
	public MdmEmpStore(BaseEmployee baseEmployee, String dateDesc, Date startTime, Date endTime, String remark, String state,
			String createdBy, Date created, String updatedBy, Date updated, Set mdmEmpStoreItems) {
		this.baseEmployee = baseEmployee;
		this.dateDesc = dateDesc;
		this.startTime = startTime;
		this.endTime = endTime;
		this.remark = remark;
		this.state = state;
		this.createdBy = createdBy;
		this.created = created;
		this.updatedBy = updatedBy;
		this.updated = updated;
		this.mdmEmpStoreItems = mdmEmpStoreItems;
	}

	// Property accessors

	public Long getEsId() {
		return this.esId;
	}

	public void setEsId(Long esId) {
		this.esId = esId;
	}

	public BaseEmployee getBaseEmployee() {
		return this.baseEmployee;
	}

	public void setBaseEmployee(BaseEmployee baseEmployee) {
		this.baseEmployee = baseEmployee;
	}

	public String getDateDesc() {
		return this.dateDesc;
	}

	public void setDateDesc(String dateDesc) {
		this.dateDesc = dateDesc;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public Set getMdmEmpStoreItems() {
		return this.mdmEmpStoreItems;
	}

	public void setMdmEmpStoreItems(Set mdmEmpStoreItems) {
		this.mdmEmpStoreItems = mdmEmpStoreItems;
	}

}