package com.winchannel.base.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;

/**
 * BaseUser generated by MyEclipse Persistence Tools
 */

public class BaseUser implements java.io.Serializable {

	// Fields

	private Long userId;

	private BaseEmployee baseEmployee;

	private BaseResource baseResource;

	private String userAccount;

	private String userPassword;

	private String userType;

	private Date lastPassDate;

	private Date lastLogin;

	private Long loginCount;

	private String empAuth;

	private String empCascadeAuth;

	private String orgAuth;

	private String prodAuth;
	
	private String homeParam;

	private String remark;

	private String state;

	private Long sort;

	private String createdBy;
	
	private Date created;
	
	private String updatedBy;
	
	private Date updated;
	
	private String roleNames="";

	public String getRoleNames() {
		Iterator<BaseUserRole> it=baseUserRoles.iterator();
		StringBuffer strbuf=new StringBuffer();
		while(it.hasNext()){
			BaseUserRole baseUserRole=(BaseUserRole)it.next();
			strbuf.append(baseUserRole.getBaseRole().getRoleName()+",");
		}
		return strbuf.toString().equals("")?"":strbuf.toString().substring(0, strbuf.toString().length()-1);
	}

	private Set baseUserRoles = new HashSet(0);

	private Set baseLogs = new HashSet(0);

	// Constructors

	/** default constructor */
	public BaseUser() {
	}

	// Property accessors

	public String getEmpAuth() {
		return empAuth;
	}

	public void setEmpAuth(String empAuth) {
		this.empAuth = empAuth;
	}

	public String getOrgAuth() {
		return orgAuth;
	}

	public void setOrgAuth(String orgAuth) {
		this.orgAuth = orgAuth;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public BaseEmployee getBaseEmployee() {
		return this.baseEmployee;
	}

	public void setBaseEmployee(BaseEmployee baseEmployee) {
		this.baseEmployee = baseEmployee;
	}

	public String getUserAccount() {
		return this.userAccount;
	}

	public void setUserAccount(String userAccount) {
		this.userAccount = userAccount;
	}

	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	public Date getLastPassDate() {
		return this.lastPassDate;
	}

	public void setLastPassDate(Date lastPassDate) {
		this.lastPassDate = lastPassDate;
	}

	public Date getLastLogin() {
		return this.lastLogin;
	}

	public void setLastLogin(Date lastLogin) {
		this.lastLogin = lastLogin;
	}

	public Long getLoginCount() {
		return this.loginCount;
	}

	public void setLoginCount(Long loginCount) {
		this.loginCount = loginCount;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Long getSort() {
		return this.sort;
	}

	public void setSort(Long sort) {
		this.sort = sort;
	}

	public Set getBaseUserRoles() {
		return this.baseUserRoles;
	}

	public void setBaseUserRoles(Set baseUserRoles) {
		this.baseUserRoles = baseUserRoles;
	}

	public Set getBaseLogs() {
		return this.baseLogs;
	}

	public void setBaseLogs(Set baseLogs) {
		this.baseLogs = baseLogs;
	}

	public String getProdAuth() {
		return prodAuth;
	}

	public void setProdAuth(String prodAuth) {
		this.prodAuth = prodAuth;
	}

	public String getUserType() {
		return userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getUpdated() {
		return updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public String getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public String getEmpCascadeAuth() {
		return empCascadeAuth;
	}

	public void setEmpCascadeAuth(String empCascadeAuth) {
		this.empCascadeAuth = empCascadeAuth;
	}

	public BaseResource getBaseResource() {
		return baseResource;
	}

	public void setBaseResource(BaseResource baseResource) {
		this.baseResource = baseResource;
	}

	public String getHomeParam() {
		return homeParam;
	}

	public void setHomeParam(String homeParam) {
		this.homeParam = homeParam;
	}

}