package com.winchannel.base.model;

import java.util.HashSet;
import java.util.Set;

/**
 * BaseDept generated by MyEclipse Persistence Tools
 */

public class BaseDept implements java.io.Serializable {

	// Fields

	private Long deptId;

	private BaseOrg baseOrg;

	private String deptName;

	private String deptAlias;

	private String deptNameEn;

	private String phone;

	private String fax;

	private String email;

	private String webside;

	private String remark;

	private String state;

	private Long sort;

	private Set baseEmployees = new HashSet(0);

	// Constructors

	/** default constructor */
	public BaseDept() {
	}

	/** full constructor */
	public BaseDept(BaseOrg baseOrg, String deptName, String deptAlias, String deptNameEn, String phone, String fax,
			String email, String webside, String remark, String state, Long sort, Set baseEmployees) {
		this.baseOrg = baseOrg;
		this.deptName = deptName;
		this.deptAlias = deptAlias;
		this.deptNameEn = deptNameEn;
		this.phone = phone;
		this.fax = fax;
		this.email = email;
		this.webside = webside;
		this.remark = remark;
		this.state = state;
		this.sort = sort;
		this.baseEmployees = baseEmployees;
	}

	// Property accessors

	public Long getDeptId() {
		return this.deptId;
	}

	public void setDeptId(Long deptId) {
		this.deptId = deptId;
	}

	public BaseOrg getBaseOrg() {
		return this.baseOrg;
	}

	public void setBaseOrg(BaseOrg baseOrg) {
		this.baseOrg = baseOrg;
	}

	public String getDeptName() {
		return this.deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	public String getDeptAlias() {
		return this.deptAlias;
	}

	public void setDeptAlias(String deptAlias) {
		this.deptAlias = deptAlias;
	}

	public String getDeptNameEn() {
		return this.deptNameEn;
	}

	public void setDeptNameEn(String deptNameEn) {
		this.deptNameEn = deptNameEn;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getWebside() {
		return this.webside;
	}

	public void setWebside(String webside) {
		this.webside = webside;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Long getSort() {
		return this.sort;
	}

	public void setSort(Long sort) {
		this.sort = sort;
	}

	public Set getBaseEmployees() {
		return this.baseEmployees;
	}

	public void setBaseEmployees(Set baseEmployees) {
		this.baseEmployees = baseEmployees;
	}

}