package com.winchannel.base.model;

import java.util.HashSet;
import java.util.Set;

/**
 * BaseDict generated by MyEclipse Persistence Tools
 */

public class BaseDict implements java.io.Serializable {

	// Fields

	private String dictId;

	private String dictName;

	private String dictType;

	private String remark;

	private String state;

	private Long sort;
	
	private boolean update;

	private Set baseDictItems = new HashSet(0);

	// Constructors

	/** default constructor */
	public BaseDict() {
	}

	/** full constructor */
	public BaseDict(String dictName, String dictType, String remark, String state, Long sort, Set baseDictItems) {
		this.dictName = dictName;
		this.dictType = dictType;
		this.remark = remark;
		this.state = state;
		this.sort = sort;
		this.baseDictItems = baseDictItems;
	}

	// Property accessors

	public String getDictId() {
		return this.dictId;
	}

	public void setDictId(String dictId) {
		this.dictId = dictId;
	}

	public String getDictName() {
		return this.dictName;
	}

	public void setDictName(String dictName) {
		this.dictName = dictName;
	}

	public String getDictType() {
		return this.dictType;
	}

	public void setDictType(String dictType) {
		this.dictType = dictType;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Long getSort() {
		return this.sort;
	}

	public void setSort(Long sort) {
		this.sort = sort;
	}

	public Set getBaseDictItems() {
		return this.baseDictItems;
	}

	public void setBaseDictItems(Set baseDictItems) {
		this.baseDictItems = baseDictItems;
	}

	public boolean isUpdate() {
		return update;
	}

	public void setUpdate(boolean update) {
		this.update = update;
	}

}