package com.winchannel.base.model;

import java.util.HashSet;
import java.util.Set;

/**
 * BaseDataAuth generated by MyEclipse Persistence Tools
 */

public class BaseDataAuth implements java.io.Serializable {

	// Fields

	private Long dataAuthId;

	private String dataAuthCode;

	private String dataAuthName;

	private Long dataAuthLevel;

	private String dataAuthExp;

	private String remark;

	private String state;

	private Long sort;

	private Set baseRoles = new HashSet(0);

	// Constructors

	/** default constructor */
	public BaseDataAuth() {
	}

	/** full constructor */
	public BaseDataAuth(String dataAuthCode, String dataAuthName, Long dataAuthLevel, String dataAuthExp,
			String remark, String state, Long sort, Set baseRoles) {
		this.dataAuthCode = dataAuthCode;
		this.dataAuthName = dataAuthName;
		this.dataAuthLevel = dataAuthLevel;
		this.dataAuthExp = dataAuthExp;
		this.remark = remark;
		this.state = state;
		this.sort = sort;
		this.baseRoles = baseRoles;
	}

	// Property accessors

	public Long getDataAuthId() {
		return this.dataAuthId;
	}

	public void setDataAuthId(Long dataAuthId) {
		this.dataAuthId = dataAuthId;
	}

	public String getDataAuthCode() {
		return this.dataAuthCode;
	}

	public void setDataAuthCode(String dataAuthCode) {
		this.dataAuthCode = dataAuthCode;
	}

	public String getDataAuthName() {
		return this.dataAuthName;
	}

	public void setDataAuthName(String dataAuthName) {
		this.dataAuthName = dataAuthName;
	}

	public Long getDataAuthLevel() {
		return this.dataAuthLevel;
	}

	public void setDataAuthLevel(Long dataAuthLevel) {
		this.dataAuthLevel = dataAuthLevel;
	}

	public String getDataAuthExp() {
		return this.dataAuthExp;
	}

	public void setDataAuthExp(String dataAuthExp) {
		this.dataAuthExp = dataAuthExp;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Long getSort() {
		return this.sort;
	}

	public void setSort(Long sort) {
		this.sort = sort;
	}

	public Set getBaseRoles() {
		return this.baseRoles;
	}

	public void setBaseRoles(Set baseRoles) {
		this.baseRoles = baseRoles;
	}

}