package com.winchannel.base.model;

import java.util.Date;

/**
 * BaseOrg generated by MyEclipse Persistence Tools
 */

public class BaseOrgLog implements java.io.Serializable {

	// Fields

	private Long id;

	private Long orgId;

	private BaseDictItem baseDictItem;

	private BaseOrg baseOrg;

	private BaseEmployee baseEmployee;

	private String orgCode;

	private String extCode;

	private String subCode;

	private Long levelCode;

	private String orgName;

	private String orgAlias;

	private String orgNameEn;

	private String principal;

	private String phone;

	private String fax;

	private String orgAddr;

	private String postCode;

	private String email;

	private String website;
	
	private String memo1;
	
	private String memo2;
	
	private String memo3;

	private String remark;

	private String state;

	private Long sort;
	
	private String createdBy;
	
	private Date created;
	
	private String updatedBy;
	
	private Date updated;
	
	private Long pi1;
	private Long pi2;
	private Long pi3;
	private Long pi4;
	private Long pi5;
	private Long pi6;
	private Long pi7;
	private Long pi8;
	private String pn1;
	private String pn2;
	private String pn3;
	private String pn4;
	private String pn5;
	private String pn6;
	private String pn7;
	private String pn8;
	private String pnall;
	
	private Date startDate;
	private Date endDate;


	// Constructors

	/** default constructor */
	public BaseOrgLog() {
	}

	// Property accessors

	public Long getOrgId() {
		return this.orgId;
	}

	public void setOrgId(Long orgId) {
		this.orgId = orgId;
	}

	public BaseDictItem getBaseDictItem() {
		return this.baseDictItem;
	}

	public void setBaseDictItem(BaseDictItem baseDictItem) {
		this.baseDictItem = baseDictItem;
	}

	public BaseOrg getBaseOrg() {
		return this.baseOrg;
	}

	public void setBaseOrg(BaseOrg baseOrg) {
		this.baseOrg = baseOrg;
	}

	public String getOrgCode() {
		return this.orgCode;
	}

	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

	public String getExtCode() {
		return this.extCode;
	}

	public void setExtCode(String extCode) {
		this.extCode = extCode;
	}

	public String getSubCode() {
		return this.subCode;
	}

	public void setSubCode(String subCode) {
		this.subCode = subCode;
	}

	public Long getLevelCode() {
		return this.levelCode;
	}

	public void setLevelCode(Long levelCode) {
		this.levelCode = levelCode;
	}

	public String getOrgName() {
		return this.orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	public String getOrgAlias() {
		return this.orgAlias;
	}

	public void setOrgAlias(String orgAlias) {
		this.orgAlias = orgAlias;
	}

	public String getOrgNameEn() {
		return this.orgNameEn;
	}

	public void setOrgNameEn(String orgNameEn) {
		this.orgNameEn = orgNameEn;
	}

	public String getPrincipal() {
		return this.principal;
	}

	public void setPrincipal(String principal) {
		this.principal = principal;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getOrgAddr() {
		return this.orgAddr;
	}

	public void setOrgAddr(String orgAddr) {
		this.orgAddr = orgAddr;
	}

	public String getPostCode() {
		return this.postCode;
	}

	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Long getSort() {
		return this.sort;
	}

	public void setSort(Long sort) {
		this.sort = sort;
	}

	public String getMemo1() {
		return memo1;
	}

	public void setMemo1(String memo1) {
		this.memo1 = memo1;
	}

	public String getMemo2() {
		return memo2;
	}

	public void setMemo2(String memo2) {
		this.memo2 = memo2;
	}

	public String getMemo3() {
		return memo3;
	}

	public void setMemo3(String memo3) {
		this.memo3 = memo3;
	}

	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getUpdated() {
		return updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public String getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Long getPi1() {
		return pi1;
	}

	public void setPi1(Long pi1) {
		this.pi1 = pi1;
	}

	public Long getPi2() {
		return pi2;
	}

	public void setPi2(Long pi2) {
		this.pi2 = pi2;
	}

	public Long getPi3() {
		return pi3;
	}

	public void setPi3(Long pi3) {
		this.pi3 = pi3;
	}

	public Long getPi4() {
		return pi4;
	}

	public void setPi4(Long pi4) {
		this.pi4 = pi4;
	}

	public Long getPi5() {
		return pi5;
	}

	public void setPi5(Long pi5) {
		this.pi5 = pi5;
	}

	public Long getPi6() {
		return pi6;
	}

	public void setPi6(Long pi6) {
		this.pi6 = pi6;
	}

	public Long getPi7() {
		return pi7;
	}

	public void setPi7(Long pi7) {
		this.pi7 = pi7;
	}

	public Long getPi8() {
		return pi8;
	}

	public void setPi8(Long pi8) {
		this.pi8 = pi8;
	}

	public String getPn1() {
		return pn1;
	}

	public void setPn1(String pn1) {
		this.pn1 = pn1;
	}

	public String getPn2() {
		return pn2;
	}

	public void setPn2(String pn2) {
		this.pn2 = pn2;
	}

	public String getPn3() {
		return pn3;
	}

	public void setPn3(String pn3) {
		this.pn3 = pn3;
	}

	public String getPn4() {
		return pn4;
	}

	public void setPn4(String pn4) {
		this.pn4 = pn4;
	}

	public String getPn5() {
		return pn5;
	}

	public void setPn5(String pn5) {
		this.pn5 = pn5;
	}

	public String getPn6() {
		return pn6;
	}

	public void setPn6(String pn6) {
		this.pn6 = pn6;
	}

	public String getPn7() {
		return pn7;
	}

	public void setPn7(String pn7) {
		this.pn7 = pn7;
	}

	public String getPn8() {
		return pn8;
	}

	public void setPn8(String pn8) {
		this.pn8 = pn8;
	}

	public String getPnall() {
		return pnall;
	}

	public void setPnall(String pnall) {
		this.pnall = pnall;
	}

	public BaseEmployee getBaseEmployee() {
		return baseEmployee;
	}

	public void setBaseEmployee(BaseEmployee baseEmployee) {
		this.baseEmployee = baseEmployee;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

}