package com.winchannel.base.model;

/**
 * BaseMessRes generated by MyEclipse Persistence Tools
 */

public class BaseMessRes implements java.io.Serializable {

	// Fields

	private BaseMessResId id;

	private String messValue;

	private Long sort;
	
	private String state;

	// Constructors

	/** default constructor */
	public BaseMessRes() {
	}

	/** minimal constructor */
	public BaseMessRes(BaseMessResId id) {
		this.id = id;
	}

	/** full constructor */
	public BaseMessRes(BaseMessResId id, String messValue, Long sort, String state) {
		this.id = id;
		this.messValue = messValue;
		this.sort = sort;
		this.state = state;
	}

	// Property accessors

	public BaseMessResId getId() {
		return this.id;
	}

	public void setId(BaseMessResId id) {
		this.id = id;
	}

	public String getMessValue() {
		return this.messValue;
	}

	public void setMessValue(String messValue) {
		this.messValue = messValue;
	}

	public Long getSort() {
		return this.sort;
	}

	public void setSort(Long sort) {
		this.sort = sort;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

}