package com.winchannel.base.model;

import java.util.HashSet;
import java.util.Set;

/**
 * BaseRole generated by MyEclipse Persistence Tools
 */

public class BaseRole implements java.io.Serializable {

	// Fields

	private Long roleId;

	private BaseDataAuth baseDataAuth;

	private String roleName;

	private String allowDel;

	private String defaultRole;

	private String remark;

	private String state;

	private Long sort;

	private Set baseUserRoles = new HashSet(0);

	private Set baseAuths = new HashSet(0);

	// Constructors

	/** default constructor */
	public BaseRole() {
	}

	/** full constructor */
	public BaseRole(BaseDataAuth baseDataAuth, String roleName, String allowDel, String defaultRole, String remark,
			String state, Long sort, Set baseUserRoles, Set baseAuths) {
		this.baseDataAuth = baseDataAuth;
		this.roleName = roleName;
		this.allowDel = allowDel;
		this.defaultRole = defaultRole;
		this.remark = remark;
		this.state = state;
		this.sort = sort;
		this.baseUserRoles = baseUserRoles;
		this.baseAuths = baseAuths;
	}

	// Property accessors

	public Long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	public BaseDataAuth getBaseDataAuth() {
		return this.baseDataAuth;
	}

	public void setBaseDataAuth(BaseDataAuth baseDataAuth) {
		this.baseDataAuth = baseDataAuth;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getAllowDel() {
		return this.allowDel;
	}

	public void setAllowDel(String allowDel) {
		this.allowDel = allowDel;
	}

	public String getDefaultRole() {
		return this.defaultRole;
	}

	public void setDefaultRole(String defaultRole) {
		this.defaultRole = defaultRole;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Long getSort() {
		return this.sort;
	}

	public void setSort(Long sort) {
		this.sort = sort;
	}

	public Set getBaseUserRoles() {
		return this.baseUserRoles;
	}

	public void setBaseUserRoles(Set baseUserRoles) {
		this.baseUserRoles = baseUserRoles;
	}

	public Set getBaseAuths() {
		return this.baseAuths;
	}

	public void setBaseAuths(Set baseAuths) {
		this.baseAuths = baseAuths;
	}

}