package com.winchannel.base.model;

/**
 * BaseUserRole generated by MyEclipse Persistence Tools
 */

public class BaseUserRole implements java.io.Serializable {

	// Fields

	private Long userRoleId;

	private BaseUser baseUser;

	private BaseRole baseRole;

	// Constructors

	/** default constructor */
	public BaseUserRole() {
	}

	/** full constructor */
	public BaseUserRole(BaseUser baseUser, BaseRole baseRole) {
		this.baseUser = baseUser;
		this.baseRole = baseRole;
	}

	// Property accessors

	public Long getUserRoleId() {
		return this.userRoleId;
	}

	public void setUserRoleId(Long userRoleId) {
		this.userRoleId = userRoleId;
	}

	public BaseUser getBaseUser() {
		return this.baseUser;
	}

	public void setBaseUser(BaseUser baseUser) {
		this.baseUser = baseUser;
	}

	public BaseRole getBaseRole() {
		return this.baseRole;
	}

	public void setBaseRole(BaseRole baseRole) {
		this.baseRole = baseRole;
	}

}