package com.winchannel.base.model;

/**
 * BaseAuth generated by MyEclipse Persistence Tools
 */

public class BaseAuth implements java.io.Serializable {

	// Fields

	private Long authId;

	private BaseRole baseRole;

	private BaseResource baseResource;

	// Constructors

	/** default constructor */
	public BaseAuth() {
	}

	/** full constructor */
	public BaseAuth(BaseRole baseRole, BaseResource baseResource) {
		this.baseRole = baseRole;
		this.baseResource = baseResource;
	}

	// Property accessors

	public Long getAuthId() {
		return this.authId;
	}

	public void setAuthId(Long authId) {
		this.authId = authId;
	}

	public BaseRole getBaseRole() {
		return this.baseRole;
	}

	public void setBaseRole(BaseRole baseRole) {
		this.baseRole = baseRole;
	}

	public BaseResource getBaseResource() {
		return this.baseResource;
	}

	public void setBaseResource(BaseResource baseResource) {
		this.baseResource = baseResource;
	}

}