package com.winchannel.base.model;

import java.util.HashSet;
import java.util.Set;

/**
 * BaseJob generated by MyEclipse Persistence Tools
 */

public class BaseJob implements java.io.Serializable {

	// Fields

	private String jobCode;

	private String jobName;

	private String remark;

	private String state;

	private Long sort;

	private Set baseJobLogs = new HashSet(0);

	// Constructors

	/** default constructor */
	public BaseJob() {
	}

	/** full constructor */
	public BaseJob(String jobName, String remark, String state, Long sort, Set baseJobLogs) {
		this.jobName = jobName;
		this.remark = remark;
		this.state = state;
		this.sort = sort;
		this.baseJobLogs = baseJobLogs;
	}

	// Property accessors

	public String getJobCode() {
		return this.jobCode;
	}

	public void setJobCode(String jobCode) {
		this.jobCode = jobCode;
	}

	public String getJobName() {
		return this.jobName;
	}

	public void setJobName(String jobName) {
		this.jobName = jobName;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Long getSort() {
		return this.sort;
	}

	public void setSort(Long sort) {
		this.sort = sort;
	}

	public Set getBaseJobLogs() {
		return this.baseJobLogs;
	}

	public void setBaseJobLogs(Set baseJobLogs) {
		this.baseJobLogs = baseJobLogs;
	}

}