package com.winchannel.base.model;

import java.util.HashSet;
import java.util.Set;

/**
 * BaseMenu generated by MyEclipse Persistence Tools
 */

public class BaseMenu implements java.io.Serializable {

	// Fields

	private Long menuId;

	private BaseMenu baseMenu;

	private BaseResource baseResource;

	private String menuCode;

	private String subCode;

	private Long levelCode;

	private String menuName;

	private String menuHint;

	private String resParams;

	private String remark;

	private String state;

	private Long sort;

	private Set baseMenus = new HashSet(0);

	// Constructors

	/** default constructor */
	public BaseMenu() {
	}

	/** full constructor */
	public BaseMenu(BaseMenu baseMenu, BaseResource baseResource, String menuCode, String subCode, Long levelCode,
			String menuName, String menuHint, String resParams, String remark, String state, Long sort, Set baseMenus) {
		this.baseMenu = baseMenu;
		this.baseResource = baseResource;
		this.menuCode = menuCode;
		this.subCode = subCode;
		this.levelCode = levelCode;
		this.menuName = menuName;
		this.menuHint = menuHint;
		this.resParams = resParams;
		this.remark = remark;
		this.state = state;
		this.sort = sort;
		this.baseMenus = baseMenus;
	}

	// Property accessors

	public Long getMenuId() {
		return this.menuId;
	}

	public void setMenuId(Long menuId) {
		this.menuId = menuId;
	}

	public BaseMenu getBaseMenu() {
		return this.baseMenu;
	}

	public void setBaseMenu(BaseMenu baseMenu) {
		this.baseMenu = baseMenu;
	}

	public BaseResource getBaseResource() {
		return this.baseResource;
	}

	public void setBaseResource(BaseResource baseResource) {
		this.baseResource = baseResource;
	}

	public String getMenuCode() {
		return this.menuCode;
	}

	public void setMenuCode(String menuCode) {
		this.menuCode = menuCode;
	}

	public String getSubCode() {
		return this.subCode;
	}

	public void setSubCode(String subCode) {
		this.subCode = subCode;
	}

	public Long getLevelCode() {
		return this.levelCode;
	}

	public void setLevelCode(Long levelCode) {
		this.levelCode = levelCode;
	}

	public String getMenuName() {
		return this.menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	public String getMenuHint() {
		return this.menuHint;
	}

	public void setMenuHint(String menuHint) {
		this.menuHint = menuHint;
	}

	public String getResParams() {
		return this.resParams;
	}

	public void setResParams(String resParams) {
		this.resParams = resParams;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Long getSort() {
		return this.sort;
	}

	public void setSort(Long sort) {
		this.sort = sort;
	}

	public Set getBaseMenus() {
		return this.baseMenus;
	}

	public void setBaseMenus(Set baseMenus) {
		this.baseMenus = baseMenus;
	}

}