package com.winchannel.mdm.distributor.model;

import java.util.Date;

import com.winchannel.base.model.BaseDictItem;
import com.winchannel.base.model.BaseOrg;

/**
 * MdmDistributorLog generated by MyEclipse Persistence Tools
 */

public class MdmDistributorLog implements java.io.Serializable {

	// Fields

	private Long id;

	private Long distId;

	private BaseDictItem baseDictItem;
	private BaseOrg baseOrg;
	private MdmDistributor mdmDistributor;

	private String distName;

	private String distCode;

	private String subCode;

	private Long levelCode;

	private String distAddr;

	private String distTel;

	private String distPost;

	private String mgrName;

	private String mgrTel;

	private String linkmanName;

	private String linkmanTel;

	private Date instDate;

	private Date checkDate;

	private Date mappingDate;

	private String memo1;

	private String memo2;

	private String memo3;

	private String memo4;

	private String memo5;

	private String memo6;

	private String remark;

	private String state;

	private Long sort;

	private String createdBy;

	private Date created;

	private String updatedBy;

	private Date updated;

	private Date passBackDate;

	private Date passDataDate;

	private Date endPassDate;

	private Date startDate;

	private Date endDate;

	// Constructors

	/** default constructor */
	public MdmDistributorLog() {
	}

	/** minimal constructor */
	public MdmDistributorLog(Long distId) {
		this.distId = distId;
	}

	/** full constructor */

	// Property accessors
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getDistId() {
		return this.distId;
	}

	public void setDistId(Long distId) {
		this.distId = distId;
	}

	public BaseDictItem getBaseDictItem() {
		return baseDictItem;
	}

	public void setBaseDictItem(BaseDictItem baseDictItem) {
		this.baseDictItem = baseDictItem;
	}

	public BaseOrg getBaseOrg() {
		return baseOrg;
	}

	public void setBaseOrg(BaseOrg baseOrg) {
		this.baseOrg = baseOrg;
	}

	public MdmDistributor getMdmDistributor() {
		return mdmDistributor;
	}

	public void setMdmDistributor(MdmDistributor mdmDistributor) {
		this.mdmDistributor = mdmDistributor;
	}

	public String getDistName() {
		return this.distName;
	}

	public void setDistName(String distName) {
		this.distName = distName;
	}

	public String getDistCode() {
		return this.distCode;
	}

	public void setDistCode(String distCode) {
		this.distCode = distCode;
	}

	public String getSubCode() {
		return this.subCode;
	}

	public void setSubCode(String subCode) {
		this.subCode = subCode;
	}

	public Long getLevelCode() {
		return this.levelCode;
	}

	public void setLevelCode(Long levelCode) {
		this.levelCode = levelCode;
	}

	public String getDistAddr() {
		return this.distAddr;
	}

	public void setDistAddr(String distAddr) {
		this.distAddr = distAddr;
	}

	public String getDistTel() {
		return this.distTel;
	}

	public void setDistTel(String distTel) {
		this.distTel = distTel;
	}

	public String getDistPost() {
		return this.distPost;
	}

	public void setDistPost(String distPost) {
		this.distPost = distPost;
	}

	public String getMgrName() {
		return this.mgrName;
	}

	public void setMgrName(String mgrName) {
		this.mgrName = mgrName;
	}

	public String getMgrTel() {
		return this.mgrTel;
	}

	public void setMgrTel(String mgrTel) {
		this.mgrTel = mgrTel;
	}

	public String getLinkmanName() {
		return this.linkmanName;
	}

	public void setLinkmanName(String linkmanName) {
		this.linkmanName = linkmanName;
	}

	public String getLinkmanTel() {
		return this.linkmanTel;
	}

	public void setLinkmanTel(String linkmanTel) {
		this.linkmanTel = linkmanTel;
	}

	public Date getInstDate() {
		return this.instDate;
	}

	public void setInstDate(Date instDate) {
		this.instDate = instDate;
	}

	public Date getCheckDate() {
		return this.checkDate;
	}

	public void setCheckDate(Date checkDate) {
		this.checkDate = checkDate;
	}

	public Date getMappingDate() {
		return this.mappingDate;
	}

	public void setMappingDate(Date mappingDate) {
		this.mappingDate = mappingDate;
	}

	public String getMemo1() {
		return this.memo1;
	}

	public void setMemo1(String memo1) {
		this.memo1 = memo1;
	}

	public String getMemo2() {
		return this.memo2;
	}

	public void setMemo2(String memo2) {
		this.memo2 = memo2;
	}

	public String getMemo3() {
		return this.memo3;
	}

	public void setMemo3(String memo3) {
		this.memo3 = memo3;
	}

	public String getMemo4() {
		return this.memo4;
	}

	public void setMemo4(String memo4) {
		this.memo4 = memo4;
	}

	public String getMemo5() {
		return this.memo5;
	}

	public void setMemo5(String memo5) {
		this.memo5 = memo5;
	}

	public String getMemo6() {
		return this.memo6;
	}

	public void setMemo6(String memo6) {
		this.memo6 = memo6;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Long getSort() {
		return this.sort;
	}

	public void setSort(Long sort) {
		this.sort = sort;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public Date getPassBackDate() {
		return this.passBackDate;
	}

	public void setPassBackDate(Date passBackDate) {
		this.passBackDate = passBackDate;
	}

	public Date getPassDataDate() {
		return this.passDataDate;
	}

	public void setPassDataDate(Date passDataDate) {
		this.passDataDate = passDataDate;
	}

	public Date getEndPassDate() {
		return this.endPassDate;
	}

	public void setEndPassDate(Date endPassDate) {
		this.endPassDate = endPassDate;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

}